### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by phun** [daveconservatoire/dcsite#1]
## What

One of the best features a code repository can have is a great README. The README should be able to tell someone, who might not even know what the project is, how to get a local version of the project up and running on their computer so they can start playing around with it.

Things it should include are:
- Requirements needed (e.g. MySQL, PHP)
- Installation instructions (command line functions to call)
- Technical information (e.g. what web technologies we use)
- Guidelines to follow in order to contribute to the repository (e.g. how to pick a bug to work on, how to submit a code review)
## Why

New developers to the project will be able to do more of the on-boarding on their own, saving us (and them) time. The faster they can set up, the faster they can contribute 😋
## Plan

For this project, I think we just need to let them know how to get it interacting with dcadmin.

As I get this repos up and running for myself, I'll add in the information that I think will help someone else get set up in the future.
## Examples

_These are libraries and not sites, but I'll find better examples later_
- https://github.com/FriendsOfPHP/Goutte
- https://github.com/facebook/react

**Comment by daveconservatoire** [comment]
I think I could have a good go at this!  And then maybe you could add anything thing you think it missing once you've been through the process of setup for yourself?

**Comment by daveconservatoire** [comment]
I've added some information from the wiki to the readme - which will be good for new users to follow.  If there's anything else to add let me know!

**Comment by phun** [comment]
Thanks Dave! I'll take a look at it.

Btw, I work in PHP-land every day at work so I've learn to love it :)
