### ISSUE TITLE
Use Composer to handle dependencies (e.g. Yii framework)

### ISSUE THREAD

**Issue by phun** [daveconservatoire/dcsite#2]
## What

Use [Composer](https://getcomposer.org/) to handle PHP dependencies such as Yii. 

The way it works is that when the repository is cloned onto a computer, a command will run to download the dependencies into the repository.
## Why

Currently, the repo has all of the Yii framework files within it. This makes it hard to know what files are specifically for Dave Conservatoire, and what files are part of the framework.

After this improvement is complete, frameworks will not be included in this repository anymore. This will keep the repository small, simple, and clean.
## Plan

Figure out what all of our PHP dependencies are, add them to Composer, and import only Composer.

Yii has [documentation](http://www.yiiframework.com/wiki/392/creating-yii-applications-with-composer/) for this

**Comment by daveconservatoire** [comment]
Sounds very helpful - I'm guessing other dependencies might be jQuery and the Khan Academy framework - although I have made quite significant modifications to this.

**Comment by phun** [comment]
I'll keep that in mind as I try to tackle this. Still think its possible though :)
