### ISSUE TITLE
update schema for project setup

### ISSUE THREAD

**Issue by wilkerlucio** [daveconservatoire/dcsite#5]
While doing the setup of the project I noticed the database schema for import is currently outdated.

I could notice 3 fields were missing:

- `homepage_order` at `Course` table
- `firstip` and `biog` at `User` table

It's possible to have more, so just in case I suggest we generate a new dump with the structure and base data to update the current schema file.

**Comment by daveconservatoire** [comment]
I have updated the DB schema - hopefully should be working now.
